create table topicos (
        id bigint generated by default as identity,
        autor varchar(255),
        curso varchar(255),
        data_criacao timestamp(6),
        mensagem TEXT,
        titulo varchar(255),
        topico_ativo boolean,
        primary key (id)
    )